name: ci

on:
  push:
    branches:
      - "master"

jobs:
  build_and_push_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/master_dotnet:latest
          
#   # work_on_server:
#   #   runs-on: ubuntu-latest
#   #   steps:
#   #     - name: work on Server
#   #       uses: appleboy/ssh-action@master
#   #       with:
#   #         host: ${{ secrets.SERVER_HOST }}
#   #         username: ${{secrets.SERVER_USER }}
#   #         key: ${{ secrets.PRIVATE_KEY }}
#   #         port: ${{ secrets.SERVER_PORT }}

#   #         script: |
#   #           ls
#   #           cd Projects
#   #           kubectl get pods
#   #           kubectl delete -f hh.yaml
#   #           kubectl apply -f hh.yaml
#   #           kubectl get deployments 

#   # sending_telegram_notification:
#   #   runs-on: ubuntu-latest
#   #   steps:
#   #     - name: send notification to telegram 
#   #       uses: appleboy/telegram-action@master
#   #       with:
#   #         to: ${{ secrets.TELEGRAM_TO }}
#   #         token: ${{ secrets.TELEGRAM_TOKEN }}
#   #         message: |
#   #           ${{ github.actor }} created commit:
#   #           Commit message: ${{ github.event.commits[0].message }}
            
#   #           Repository: ${{ github.repository }}
            
#   #           See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
